# Generated by Django 3.2.6 on 2021-09-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
