# Generated by Django 3.2.6 on 2021-09-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Seoul', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='010-1234-1234', max_length=45),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
