# Generated by Django 3.2.6 on 2021-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
    ]
